Server setup
Newbology/ng-rolodex pull request #3
Opened 2019-02-20 05:06 UTC by Newbology

2019-02-20 09:32 UTC, taesup requested changes

2019-02-20 09:32 UTC, taesup commented on server/server.js
> +app.use('/rolodex', rolodex);
You probably want to name the route according to the data model that you'll be sending back. Either Users or Contacts. Your data models are defined by your tables in most cases.

2019-02-20 21:43 UTC, Newbology commented
meant to branch off for migrations, committed and pushed code after making PR

2019-02-20 23:53 UTC, taesup requested changes

2019-02-20 23:53 UTC, taesup commented on database/migrations/20190219185900_foreignkey.js
> +  return knex.schema.dropTable('users');
For this migration you shouldn't be dropping the table, that's not the opposite of what the up function is doing. It should be dropping that column you just created. Nothing you can do now for this though but keep note of what you should be doing in a down function.

2019-02-20 23:53 UTC, taesup commented on server/server.js
> +app.use(express.static('public'));
express.static should come before bodyParser

2019-02-21 02:41 UTC, taesup approved these changes

2019-02-21 02:55 UTC, merged